name: Commitlint

on:
  pull_request:
    branches: [ main, next, alpha ]
  push:
    branches: [ main, next, alpha ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          
      - name: Install dependencies
        run: npm install
        
      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}